version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: lc-joyeux-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lcjoyeux
      POSTGRES_PASSWORD: lcjoyeux
      POSTGRES_DB: lcjoyeux
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 
